export {
  CV_PROFILE_SCHEMA_VERSION,
  type StandardCVLink,
  type StandardCVBasics,
  type StandardCVDateRange,
  type StandardCVExperience,
  type StandardCVEducation,
  type StandardCVSkillGroup,
  type StandardCVLanguage,
  type StandardCVNamedItem,
  type StandardCVPresentation,
  type StandardCVProfile,
  normalizeStandardCVProfile,
  normalizeContactEmail,
  buildExternalLinkHref,
  getBestCVText,
  profileToPlainText,
  getCVSourceTextHash,
} from "@/modules/cv-library/domain/cv-profile";
