export {
  type CVTemplateId,
  type CVTemplateLocale,
  type CVRenderableSectionId,
  type CVPresentationInput,
  type CVTemplateDefinition,
  CV_RENDERABLE_SECTIONS,
  DEFAULT_SECTION_ORDER,
  SECTION_LABELS,
  isRenderableSectionId,
  normalizeSectionOrder,
  normalizeSectionTitles,
  normalizeAccentColor,
  getTemplateAccentColor,
  getResolvedAccentColor,
  getOrderedRenderableSections,
  getSectionTitle,
  CV_TEMPLATES,
  getCVTemplate,
  getSectionLabels,
} from "@/backend/modules/cv-library/domain/cv-templates";
